name: Java CI with Gradle and Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 1. بنظبط الجافا الأول عشان نعمل الـ Jar فايل
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    # 2. بنبني مشروع الجافا
    - name: Build with Gradle Wrapper
      run: ./gradlew build

    # 3. بنسجل دخول على حسابك في Docker Hub (باستخدام الـ Secrets)
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 4. بنبني الـ Docker Image ونرفعها أوتوماتيك
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-java-app:latest
